const officialNotices = [
  {
    title: "关于约定的说明",
    body: "Playbit 用于记录双方自愿达成的娱乐性约定。页面中的签署与结案是产品仪式，不替代正式法律文书，也不提供强制履约服务。"
  },
  {
    title: "关于隐私与分享",
    body: "待签署链接的持有者可以查看约定内容，请只分享给预期参与者。双方签署后，合约内容仅参与双方可查看。"
  },
  {
    title: "关于结果登记",
    body: "至于现场发生了什么，我们没在现场。结果由参与者自行登记；Playbit 不核实事实，也不裁判争议。"
  }
];

export const copy = {
  common: {
    back: "返回",
    close: "关闭",
    home: "首页",
    pending: "待定",
    view: "查看",
    loading: "处理中",
    unavailable: "暂不可用",
    me: "我",
    initiator: "发起方",
    change: "更换",
    selected: "已选"
  },
  app: {
    name: "说好不许赖",
    tagline: "说好了，就记一笔。",
    oneLiner: "记录约定，随时开一盘。"
  },
  home: {
    accountAction: "账号",
    accountGuestLabel: "登录",
    heroAction: "立即签约",
    heroGameAction: "立即抽卡",
    heroGameTitle: "随机来一盘",
    heroLabel: "签约与游戏",
    functionsLabel: "常用功能",
    voucherCount: (count: number) => `${count}张`,
    voucherLogin: "登录查看",
    functions: {
      agreement: "签约",
      game: "游戏卡",
      records: "合约记录",
      vouchers: "卡券"
    },
    announcementTitle: "公告",
    announcements: officialNotices.map((notice) => notice.title),
    overviewTitle: "合约总览",
    latestPending: "最近待处理",
    latestFinished: "最近结案",
    latestEmptyTitle: "还没有合约记录",
    latestEmptyAction: "立一份约定",
    overviewLoading: "正在加载合约摘要",
    overviewLoadFailed: "合约摘要暂时没加载出来",
    overviewLoadFailedNote: "请检查网络后再试。",
    retryOverview: "重新加载",
    latestWith: (name: string) => `与 ${name}`,
    viewAgreement: "查看合约",
    overviewCount: (count: number) => count > 99 ? "99+" : String(count),
    overview: {
      pending: "待确认",
      active: "进行中",
      settling: "待兑现",
      finished: "已结案"
    },
    viewAll: "全部记录",
    gamesTitle: "热门游戏卡",
    gameTeasers: {
      "wrong-answers-only": "知道答案，也不能说对。",
      "two-truths-one-lie": "哪一句是你编的？",
      "turtle-soup-water": "一碗汤，猜一个意外。"
    },
    startGame: "开一把",
    moreGames: "再抽一张",
    playThisCard: "玩这一张",
    minutes: "分钟",
  },
  notices: {
    title: "公告与说明",
    sectionTitle: "官方说明",
    moreTitle: "其他公告",
    items: officialNotices,
    footer: "请勿在约定、签名或分享内容中填写不希望对方看到的敏感信息。"
  },
  auth: {
    guest: "未登录",
    registered: "已登录",
    account: "我的账号",
    saveAccount: "注册并登录",
    login: "登录或注册",
    email: "邮箱",
    emailDomains: ["gmail.com", "outlook.com", "qq.com", "163.com", "icloud.com", "yahoo.com", "proton.me"],
    password: "密码",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    nickname: "称呼",
    localUser: "未登录",
    emailPlaceholder: "name@example.com",
    passwordPlaceholder: "至少 8 位",
    saveHint: "签名将保存在当前账号中，下次签署时可直接使用或重签。",
    requiredTitle: "请先登录或注册",
    requiredHint: "为了保护合约、签名和权益卡券，当前操作需要账号身份。",
    saveFailed: "注册未完成，请稍后重试",
    loginFailed: "邮箱或密码不正确，请重试",
    loginUnavailable: "暂时无法登录，请稍后重试",
    logout: "退出登录",
    accountReady: "账号已登录",
    statusSignedIn: "已登录",
    statusGuest: "未登录",
    accountEmail: "登录邮箱",
    signatureStatus: "签名状态",
    signatureSaved: "已保存，可在签署时重签",
    signaturePending: "尚未保存",
    loginTitle: "登录后继续",
    registerTitle: "创建账号",
    loginHint: "输入邮箱和密码。首次使用时，可继续完成注册。",
    registerHint: "补充一个称呼，即可完成注册并继续。",
    completeRegisterTitle: "完成注册",
    completeRegister: "完成注册并继续",
    nicknamePlaceholder: "例如：小王",
    invalidEmail: "请输入有效的邮箱地址",
    passwordRule: "密码至少 8 位",
    accountEntry: "账号入口",
    loginStateHint: "登录状态会保留在此设备，密码可交由浏览器保存。",
    nicknameHint: "系统先替你取一个称呼，也可以改成自己的。",
    nicknameRefresh: "换一个昵称",
    nicknameSuggestions: ["花花", "萌兰", "和花", "福宝", "丫丫", "七仔", "爱宝", "乐宝"],
    editProfile: "编辑资料",
    changeAvatar: "更换头像",
    resetAvatar: "恢复默认头像",
    avatarHint: "支持 JPG、PNG、WebP，最大 5 MB",
    avatarProcessing: "正在处理头像…",
    avatarInvalid: "请选择 5 MB 以内的 JPG、PNG 或 WebP 图片。",
    avatarFailed: "图片无法处理，请换一张图片重试。",
    profileNicknameTooLong: "昵称最多 20 个字。",
    saveProfile: "保存修改",
    profileHint: "昵称会显示在你的约定和凭证中。",
    profileSaved: "资料已更新",
    profileFailed: "资料暂未更新，请稍后重试。",
    profileNicknameRequired: "请先填写一个昵称。",
    statsAgreements: "合约记录",
    statsPending: "待处理",
    statsVouchers: "权益卡券",
    statsLabel: "账号概况",
    recordLabel: "PLAYBIT RECORD",
    medalsTitle: "行为印记",
    medals: {
      firstAgreement: "初次立约",
      firstAgreementHint: "留下第一份约定",
      keeper: "说到做到",
      keeperHint: "完成一次权益履约",
      regular: "常来一局",
      regularHint: "留下三份约定记录"
    },
    close: "关闭",
    switchToRegister: "没有账号？注册",
    switchToLogin: "已有账号？登录"
  },
  create: {
    agreementTooLong: "约定事项请控制在 50 字以内。",
    stakeTooLong: "自定义权益请控制在 20 字以内。",
    navTitle: "合约草案",
    title: "合约创建",
    subtitle: "把已经说好的事写下来，再请对方签署。",
    agreement: "约定事项",
    agreementPlaceholder: "例如：谁先说“随便”，谁负责把今晚安排好",
    stake: "本次权益",
    signature: "签名",
    signatureSheetTitle: "甲方签署",
    signatureConfirm: "签署并生成",
    signatureRequired: "请先完成签名确认",
    stepAgreement: "填写约定",
    stepStake: "选择权益",
    stepSignature: "签署确认",
    nextStep: "下一步",
    nextHint: "填写完成后，下一步签署并生成。",
    draftStatus: "创建中",
    personalityLine: "不必写得复杂，你们俩能看懂就行。",
    noticeTitle: "说明与隐私",
    agreementRequired: "请先写下这次约定。",
    stakeRequired: "请填写自定义权益后再继续。",
    noticeDocumentTitle: "约定记录与隐私告知",
    noticeDocumentSubtitle: "约定记录说明",
    noticeGreeting: "参与者您好：",
    noticeParagraphs: [
      "本页面用于记录双方自愿达成的日常约定。本系统仅提供记录、签署、分享与状态展示服务，不参与现场互动。",
      "本系统只保存参与者主动提交的约定、签名和结果登记，不读取、不推断，也不判断现场实际发生的情况。至于当时到底发生了什么，我们没在现场。",
      "签署和结案属于双方之间的记录与仪式，不构成法律意义上的合同、担保、裁判或强制履行承诺。约定如何执行，由参与者自行协商。",
      "签名仅用于本系统记录，不用于其他场景，也不具备法律效力。为降低信息风险，建议使用昵称或称呼，不要填写真实姓名。"
    ],
    noticeEmphasis: "如需分享待签署链接，请先确认其中的内容是你愿意让对方看到的。",
    noticeConfirmTitle: "参与者确认",
    noticeConfirmBody: "继续使用即表示你已了解以上说明，并同意由本系统按照本说明保存和展示你主动提交的内容。",
    createFailed: "合约暂未生成，请检查网络后重试"
  },
  draw: {
    navTitle: "开一盘",
    title: "开一盘",
    cardLabel: "玩法卡",
    howToPlay: "怎么玩",
    outcomeLabel: "怎么分胜负",
    participantUnit: "人",
    drawing: "正在抽取",
    addStakes: "加点彩头",
    durationUnit: "分钟",
    readyLabel: "玩法卡",
    emptyLabel: "开一盘",
    emptyTitle: "抽取本局玩法",
    emptyContent: "抽到即可开始，不必先创建合约。",
    winCondition: "结束条件",
    togetherLabel: "直接玩",
    versusLabel: "可分胜负",
    reveal: "查看谜底",
    hideReveal: "收起谜底",
    drawNow: "抽一张",
    reroll: "再抽一张"
  },
  flip: {
    navTitle: "翻盘",
    title: "翻盘邀请",
    recordTitle: "翻盘记录",
    cardLabel: "本局玩法",
    statuses: {
      pending_acceptance: "待对方接受",
      active: "进行中",
      declined: "邀请未被接受",
      settled: "结果已登记"
    },
    openRecord: "查看翻盘",
    openSource: "查看来源翻盘",
    loadingRecord: "正在加载翻盘记录",
    retryRecord: "重新加载翻盘记录",
    confirmResultTitle: "确认翻盘结果",
    confirmApplicantWon: "确认发起方获胜？本张原权益将被免除，登记后不可撤销。",
    confirmApplicantLost: "确认受邀方获胜？原权益保留，并新增一张同类权益，登记后不可撤销。",
    originalEquity: "原权益状态",
    originalWaived: "已免除",
    originalRetained: "保留待核销",
    additionalEquity: "新增权益",
    additionalPending: "新增卡券同步中，可稍后在卡券中心查看。",
    resultRecorder: "登记人",
    viewVouchers: "查看权益卡券",
    recordLater: "稍后登记",
    keepPlaying: "返回玩法",
    declinedHint: "原权益保持不变。",
    equityTitle: "沿用原权益",
    equityHint: "本局沿用原权益，不另加条件。",
    applicantLabel: "发起方",
    inviteeLabel: "受邀方",
    inviteeTitle: "翻盘邀请",
    pendingApplicant: "邀请已生成，等待对方确认。",
    pendingInvitee: "对方邀请你使用这张玩法卡进行翻盘。",
    accept: "接受翻盘",
    decline: "暂不接受",
    start: "开始这一局",
    awaiting: "等待对方开始",
    recordResult: "登记本局结果",
    applicantWon: "翻盘成功，原权益已免除。",
    applicantLost: "翻盘未成功，原权益保留，并新增一张同类权益。",
    resultDisclaimer: "结果由参与者自行登记。",
    share: "分享邀请",
    shareText: "这次不服，再来一盘？",
    refresh: "刷新状态",
    chooseWinner: "选择这一局的获胜方",
    failed: "操作未完成，请稍后重试",
    declined: "邀请未被接受",
    winnerTitle: "登记胜方"
  },
  sign: {
    title: "签署合约",
    formTitle: "签署信息",
    signer: "签署人",
    signature: "手写签名",
    action: "确认签署",
    signed: "双方已签署",
    missingLabel: "链接不可用",
    missingTitle: "无法打开这份合约",
    missingContent: "请检查链接是否完整，或请发起方重新分享。"
  },
  stakes: {
    title: "选择权益",
    selected: "已选权益",
    choose: "选择权益",
    custom: "自定义",
    customTicket: "自定义卡券",
    displayBenefit: "一次",
    assetHint: "约定权益",
    customLabel: "自定义内容",
    customPlaceholder: "例如：明天负责接孩子",
    presets: [
      { type: "coupon", label: "洗碗一次", description: "负责洗碗一次" },
      { type: "coupon", label: "请奶茶一杯", description: "请对方喝一杯奶茶" },
      { type: "coupon", label: "做饭一次", description: "负责一顿饭" },
      { type: "coupon", label: "周末安排权一次", description: "一次周末安排权" },
      { type: "point", label: "积分", description: "仅记录双方积分" },
      { type: "custom", label: "自定义权益", description: "填写双方约定的权益" }
    ]
  },
  game: {
    title: "开一把", kind: "游戏彩头", selectStake: "加点彩头", stakeTitle: "本局彩头",
    confirmStake: "确认彩头，邀请同伴", join: "确认彩头并加入", invite: "邀请同伴加入",
    waiting: "等同伴来接招", waitingHint: "对方确认后，彩头就记下了。",
    joined: "双方已确认", activeHint: "认真玩，输赢你们说了算。", guestHint: "加入后，本局权益记入你的账户。",
    participant: "参与者", opponent: "等待同伴", rules: "查看玩法", result: "登记结果",
    chooseWinner: "谁赢了这一把？", submitResult: "确认结果", resultHint: "至于当时到底发生了什么，我们没在现场。",
    createFailed: "本局未创建，请重试", joinFailed: "未能加入，请刷新查看邀请状态", failed: "暂时无法读取这局游戏",
    unavailable: "邀请已结束或已有同伴加入", retry: "重新加载", stakeHint: "小小彩头，输赢才有回响。",
    privateGame: "本局已确认，仅参与双方可查看。", loginToView: "登录查看本局",
    consent: "双方自愿确认，结果自行登记，不涉及金钱交易。", noSignature: "确认即可加入，无需签名。",
    joinedBy: (name: string) => `${name} 邀你开一把`, source: "玩法已锁定", recordNo: "本局编号",
    createdAt: "发起时间", viewRecord: "查看本局", gameCertificate: "本局确认单", recordType: "记录类型",
    waitingStatus: "待加入", alreadyJoined: "已加入", shareHint: "同伴扫码查看玩法与彩头，确认后加入。",
    recordFailure: "结果暂未记录，请刷新后重试"
  },
  contract: {
    removed: "这份合约已被发起方删除。",
    changedReview: "合约内容或状态已变化，请查看最新内容后再确认。",
    navTitle: "合约",
    documentTitle: "电子约定书",
    productLine: "君子协定，一言既出，驷马难追。",
    progressTitle: "办理进度",
    progress: {
      signing: "签署中",
      running: "进行中",
      closing: "结果已登记",
      archived: "已结案"
    },
    agreementNo: "协议编号",
    signedDate: "创建日期",
    seal: "合约正式成立",
    documentSubtitle: "双方留存 · 电子记录",
    emblem: "约",
    sealEyebrow: "双方确认",
    sealFooter: "约定留存",
    recordNote: "本记录仅用于双方生活约定，不具有法律效力。签名仅在本系统留存。",
    pendingSeal: "待乙方签署",
    confirmA: "甲方确认",
    confirmB: "乙方确认",
    signaturePending: "待签名",
    partyA: "甲方",
    partyB: "乙方",
    fallbackInitiator: "发起方",
    fallbackCounterparty: "待签署",
    waiting: "等待对方签署",
    refreshing: "正在刷新签署状态",
    refreshAction: "刷新签署状态",
    signFailed: "签署未完成，请刷新状态后重试",
    documentSave: "保存电子约定书",
    sendToCounterparty: "转给乙方签署",
    enterSession: "查看进行中",
    articleLabels: {
      first: "第一条",
      second: "第二条",
      third: "第三条",
      fourth: "第四条",
      fifth: "第五条"
    },
    stakePrefix: "双方约定的权益为",
    stakeSuffix: "；履行方式由双方自行协商。",
    clauseTitles: {
      subject: "约定事项",
      judgment: "结果登记",
      stake: "权益与履约",
      exception: "特别说明",
      effective: "生效条件"
    },
    clauseSentences: {
      subjectPrefix: "双方确认，本次约定事项为",
      subjectSuffix: "。",
      judgmentPrefix: "本次结果由双方自行确认并登记。",
      judgmentSuffix: "Playbit 仅保存参与者提交的记录。"
    },
    articles: {
      spirit: "双方基于自愿原则，就本次事项达成以下约定：",
      exception: "本合约用于记录双方约定，不提供争议裁定或强制履行。如需变更权益，由双方自行协商。",
      effective: "双方签署后，本合约生效。"
    }
  },
  session: {
    navTitle: "进行中",
    active: "本局进行中",
    settle: "登记结果",
    boost: "加码",
    boostHint: "双方确认后生效",
    boostCount: "已加码",
    boostLimit: "已达 3 次上限",
    boostPlaceholder: "例如：增加一张洗碗券",
    boostSubmit: "发起加码",
    boostConfirm: "确认这次加码",
    boostPending: "待你确认",
    boostYouConfirmed: "你已确认，等待对方",
    boostConfirmed: "已确认",
    boostFailed: "加码未提交，请稍后重试",
    boostWithdraw: "撤回加码",
    boostWithdrawn: "已撤回加码",
    boostWithdrawFailed: "未能撤回，已刷新状态。已确认的加码不可撤回。",
    stateSyncFailed: "合约状态暂未同步，请稍后重试",
    reroll: "重抽",
    accept: "接受这张",
    challenge: "本局玩法",
    judgment: "结果登记",
    stake: "权益",
    briefLabel: "当前约定",
    subjectLabel: "约定事项",
    currentStake: "当前权益",
    equityDetails: "查看完整权益",
    resultTitle: "登记结果",
    winnerChoice: "登记为获胜方",
    resultDisclaimer: "结果由参与者自行确认并登记。",
    enhancementTitle: "权益变更",
    statuses: {
      pending_signature: "待签署",
      pending_confirmation: "待加入",
      active: "进行中",
      result_recorded: "待履约",
      fulfilled: "已履约",
      waived: "已免除"
    }
  },
  settlement: {
    navTitle: "结算",
    title: "本局结算",
    agreement: "约定",
    winner: "权益获得方",
    loser: "权益提供方",
    recorder: "结果登记人",
    resultRecorder: "现场发生了什么，我们没看见；这里只保存你们登记的结果。",
    stake: "权益",
    status: "状态",
    pending: "待履约",
    fulfilled: "已履约",
    voucherIssued: "卡券已发放",
    voucherIssuedHint: "已存入卡券中心，持有人可随时查看。",
    voucherArchivedHint: "卡券处理记录可在详情中查看。",
    pointRecorded: "积分已记录",
    pointRecordedHint: "积分仅用于双方之间的记录，不可兑换现金。",
    waived: "已由双方确认免除",
    openVouchers: "查看权益卡券",
    downloadResult: "下载结果",
    shareResult: "分享结果",
    downloadAndShare: "下载并分享证书"
  },
  certificate: {
    navTitle: "开具凭证",
    agreementTitle: "电子约定书",
    resultTitle: "本局比赛证书",
    victoryTitle: "优胜证书",
    honorTitle: "风度嘉许状",
    victoryEnglish: "CERTIFICATE OF VICTORY",
    honorEnglish: "A TRIBUTE TO THE CHALLENGER",
    archiveEnglish: "CERTIFICATE OF RECORD",
    awardSeries: "生活赛事 · 个人纪念",
    awardPresented: "谨颁予",
    victoryCitation: "据参与者登记，本局胜出。特颁此证，记下这场小小的胜利。",
    honorCitation: "本局虽未胜出，仍是这场好玩的共同主角。特颁此状，留念此刻，再待下局。",
    victoryAside: "这一局，值得裱起来。",
    honorAside: "这一局没赢，下一局另说。",
    recordIssuer: "生活约定记录处",
    recordDate: "留存日期",
    recordNumber: "证书编号",
    signedWitness: "本局登记人",
    resultFact: "本局登记结果",
    victoryFact: "胜出",
    honorFact: "未胜出",
    peer: "同场参与",
    fulfillmentTitle: "履约完成证明",
    flipTitle: "翻盘结果凭证",
    waiverTitle: "权益免除凭证",
    eyebrow: "PLAYBIT · 生活记录",
    seal: "双方确认",
    agreement: "约定事项",
    winner: "权益获得方",
    provider: "权益提供方",
    equity: "约定权益",
    challenge: "本局挑战",
    effect: "权益处理",
    status: "记录状态",
    recordedBy: "结果登记",
    signedAt: "协议编号",
    resultStatus: "结果已记录",
    awardIntro: "谨此记录",
    awardRecipient: "本局获胜者",
    awardCitation: (title: string) => `在《${title}》中获胜`,
    awardSeal: "结果留存",
    waitingFulfillment: "待双方自行履行",
    fulfilledStatus: "已履约",
    flipWonStatus: "原权益已免除",
    flipLostStatus: "原权益保留，新增同类权益",
    disclaimer: "Playbit 未在现场，仅按参与者提交的信息留存。",
    share: "分享凭证",
    save: "保存图片",
    saved: "凭证图片已生成",
    shareUnavailable: "当前浏览器不支持图片分享，已为你保存图片。",
    failed: "凭证生成失败，请重试"
  },
  history: {
    navTitle: "合约记录",
    title: "合约记录",
    emptyLabel: "暂无记录",
    emptyTitle: "暂无合约记录",
    emptyContent: "下次说好了什么，就记在这里。",
    stake: "权益",
    createdAt: "创建",
    agreementNo: "协议编号",
    counterparty: "对方",
    summaryTitle: "记录总览",
    summary: (visible: number, total: number) => visible === total ? "全部记录" : `当前显示 ${visible} 份`,
    statusTabsLabel: "合约记录状态",
    statusTabs: {
      all: "全部",
      pending: "待确认",
      active: "进行中",
      result: "待兑现",
      finished: "已结案"
    },
    monthLabel: (year: string, month: string) => `${year}.${month}`,
    monthCount: (count: number) => `${count}份`,
    filterEmptyTitle: "这里还没有记录",
    filterEmptyContent: "换一个状态看看，或先说好一件事。",
    loadingMore: "正在加载更多记录",
    deleteTitle: "删除这份合约？",
    deleteMessage: (title: string) => `《${title}》尚未结案，删除后将不再保留。`,
    deleteAction: "删除合约",
    deleteSuccess: "合约已删除",
    deleteFailed: "合约未删除，请稍后重试"
  },
  share: {
    contractCta: "转给乙方签署",
    openPanel: "分享",
    panelTitle: "分享本次约定",
    panelHint: "请同伴扫码查看，或将链接发给对方。",
    signPanelTitle: "转给乙方签署",
    signPanelHint: "乙方扫码查看约定，签署后生效。",
    flipPanelTitle: "邀请对方翻盘",
    flipPanelHint: "请原权益持有人扫码，确认本次翻盘。",
    copied: "邀请链接已复制",
    copyFailed: "未能自动复制，请长按下方链接复制。",
    systemAction: "选择设备上的应用和联系人",
    nativeHint: "邀请卡将交给系统分享面板，由你选择应用和联系人。",
    imageFallback: "当前浏览器不支持图片直传，邀请卡已下载。请打开对应应用，从相册发送。",
    imageShareFailed: "暂未打开分享，可以保存邀请卡后发送。",
    imageAlt: "带二维码的邀请卡",
    copyAction: "自行发送",
    qrTitle: "扫码邀请",
    faceToFace: "面对面",
    qrAlt: "本次邀请二维码",
    qrLoading: "正在生成二维码",
    qrFailed: "二维码暂未生成",
    retry: "重新生成",
    qrHint: "扫码后查看详情",
    saveQr: "保存邀请卡",
    linkLabel: "邀请链接",
    settlementTitle: "本局结果已登记",
    copyLink: "分享结果",
    screenshotHint: "可保存凭证图片并分享。",
    channels: {
      system: "系统分享",
      copy: "复制链接"
    },
    labels: {
      agreement: "约定",
      challenge: "约定事项",
      judgment: "本局规则",
      winner: "登记胜方",
      stake: "权益",
      signLink: "签署链接",
      pending: "待签署"
    }
  },
  vouchers: {
    navTitle: "我的卡券",
    detailTitle: "卡券详情",
    aria: {
      back: "返回",
      categoryTabs: "卡券状态"
    },
    punctuation: {
      labelSeparator: "："
    },
    date: {
      month: "月",
      day: "日"
    },
    statusTabs: {
      all: "全部",
      pending: "待履约",
      available: "待核销",
      used: "已完结"
    },
    rule: "规则",
    viewAgreement: "查看合约",
    redeem: "去核销",
    confirmRedeem: "确认核销",
    redeemed: "已核销",
    received: "已发放",
    pendingAction: "待履约",
    archivedAction: "查看",
    ticketCaption: "权益卡券",
    ticketCount: (count: number) => `${count}张`,
    benefitSubtitles: {
      cup: "请一杯",
      once: "一次",
      choiceRight: "选择权",
      decisionRight: "决定权",
      routeRight: "路线权",
      additions: "含权益变更"
    },
    loadingMore: "正在加载更多",
    confirmRedeemTitle: "确认核销卡券",
    confirmRedeemText: "核销后将记录本张卡券的使用情况，此操作不可撤销。",
    redeemSuccess: "卡券已核销",
    redeemFailed: "核销失败，请稍后再试",
    openFailed: "无法打开关联合约，请稍后重试",
    agreementNo: "协议编号",
    relatedAgreement: "关联合约",
    judgmentRule: "本局规则",
    issuer: "出券方",
    holder: "持有人",
    emptyTitle: "暂无卡券",
    emptyText: "合约登记结果后，关联卡券会显示在这里。",
    detail: {
      credential: "权益卡券",
      agreement: "关联合约",
      rule: "履约规则",
      parties: "相关人员",
      issuer: "出券方",
      holder: "持有人",
      time: "时间状态"
    },
    sources: {
      signing: "待确认",
      agreement: "生活协议",
      archive: "结案归档"
    },
    pending: "待履约",
    fulfilled: "已履约",
    waived: "该权益已免除",
    waiverRecorded: "权益已免除",
    flipAction: "发起翻盘",
    graceAction: "使用赖皮券申请免除",
    graceWait: "等待持券方确认",
    graceApprove: "同意免除",
    graceReject: "保留原约定",
    gracePending: "对方申请使用赖皮券",
    graceRejected: "申请未获同意，原权益与赖皮券均保持可用。",
    graceAvailable: "赖皮券可用",
    graceReserved: "赖皮券确认中",
    graceUsed: "赖皮券已使用",
    graceTitle: "赖皮券",
    graceEdition: "珍藏权益",
    graceRareLabel: "RARE · 稀有",
    gracePrivilege: "偶尔赖一下，也算说好了。",
    graceRule: "经对方同意，可免除一项待履约权益。",
    graceSerial: "藏品编号",
    graceMark: "宽宥",
    graceEarned: "完成 10 次履约后自动获得",
    graceEmpty: "暂无赖皮券",
    graceMilestonePrefix: "第 ",
    graceMilestoneSuffix: " 次履约发放",
    graceRequestSent: "已请对方确认免除",
    graceFailed: "赖皮券操作未能完成，请刷新后重试",
    holderPending: "待结算",
    agreementStatuses: {
      pending_signature: "待签署",
      pending_confirmation: "待加入",
      active: "进行中",
      result_recorded: "待履约",
      fulfilled: "已履约",
      waived: "已免除"
    },
    overviewTitle: "卡券管理"
  },
  signature: {
    clear: "重新签名",
    hint: "建议使用昵称或称呼",
    safety: "签名仅用于本系统记录，建议不要填写真实姓名。",
    required: "请先完成手写签名"
  }
} as const;

export { cardCatalog } from "./cards.js";

export type CopyKey = typeof copy;
export { standaloneGameCopy } from "./standalone-game-copy.js";
