export const standaloneGameCopy = {
  loading: "正在准备一张卡",
  title: "开一局",
  eyebrow: "PLAYBIT · 现场游戏",
  readyHint: "抽到就玩，主持人把节奏交给现场",
  playingHint: "现场开玩，结果和彩头按你们的约定来。",
  resultHint: "本局已经留下记录，彩头由你们线下约定",
  reroll: "换一张",
  start: "开玩这张",
  finish: "添个彩头",
  backToPlay: "回到本局",
  playAgain: "再来一张同类卡",
  completed: "本局完成",
  winnerTitle: "谁赢了？",
  playerA: "玩家 A",
  playerB: "玩家 B",
  draw: "平局",
  rankingTitle: "记下现场排名",
  addPlayer: "添加玩家",
  removePlayer: "移除",
  scoreUnit: "分",
  saveResult: "生成结果",
  certificate: "比赛证书",
  certificateNote: "结果由现场登记，Playbit 只负责把这一刻留下来",
  stakeTitle: "添个彩头",
  stakeHint: "彩头由现场自行约定，Playbit 负责记录结果和发起结算。",
  startSettlement: "发起结算",
  openCertificate: "开具比赛证书",
  clearScoreboard: "清空积分",
  clearScoreboardTitle: "清空记分牌",
  clearScoreboardMessage: "当前所有玩家的积分都会归零，确定要清空吗？",
  clearScoreboardConfirm: "确认清空",
  resultRecorded: "结果已记录",
  noWinner: "只记录完成，不分胜负",
  closeTools: "收起工具",
  timer: "计时器",
  counter: "计数器",
  scoreboard: "记分牌",
  startTimer: "开始",
  pauseTimer: "暂停",
  resetTimer: "重置",
  decrement: "减一",
  increment: "加一",
  emptyCard: "正在准备一张卡",
  likeCard: "喜欢这张玩法",
  unlikeCard: "取消喜欢",
  participantRange: (min: number, max: number) => min === max ? `${min} 人` : `${min}-${max} 人`,
  duration: (minutes: number | null) => minutes ? `${minutes} 分钟` : "不限时"
} as const;
