export const standaloneGameCopy = {
  loading: "正在准备一张卡",
  title: "来一局",
  eyebrow: "PLAYBIT · 现场游戏",
  readyHint: "抽到就玩，主持人把节奏交给现场",
  playingHint: "规则在卡上，工具只在需要时出现",
  resultHint: "本局已经留下记录，彩头由你们线下约定",
  reroll: "换一张",
  start: "开玩这张",
  finish: "记录结果",
  backToPlay: "回到本局",
  playAgain: "再来一局",
  completed: "本局完成",
  winnerTitle: "谁赢了？",
  playerA: "玩家 A",
  playerB: "玩家 B",
  draw: "平局",
  rankingTitle: "记下现场排名",
  addPlayer: "添加玩家",
  removePlayer: "移除",
  scoreUnit: "分",
  saveResult: "生成结果",
  certificate: "结果预览",
  certificateNote: "这是一份由主持人登记的现场记录，Playbit 不在场",
  resultRecorded: "结果已记录",
  noWinner: "只记录完成，不分胜负",
  tools: "现场工具",
  closeTools: "收起工具",
  timer: "计时器",
  counter: "计数器",
  scoreboard: "记分牌",
  startTimer: "开始",
  pauseTimer: "暂停",
  resetTimer: "重置",
  decrement: "减一",
  increment: "加一",
  emptyCard: "正在准备一张卡",
  participantRange: (min: number, max: number) => min === max ? `${min} 人` : `${min}-${max} 人`,
  duration: (minutes: number | null) => minutes ? `${minutes} 分钟` : "不限时"
} as const;
