import "vant/es/popup/style/index.mjs";
import "vant/es/list/style/index.mjs";
import "vant/es/empty/style/index.mjs";
import "vant/es/toast/style/index.mjs";
import "vant/es/dialog/style/index.mjs";
import "./styles/tokens.css";
import "./styles/base.css";
import "./styles/product-primitives.css";
import "./styles/app-shell.css";
import "./styles/life.css";
import "./styles/life-service.css";
import "./styles/life-navigation.css";
import "./styles/life-controls.css";
import "./styles/life-overlays.css";
import "./styles/auth.css";
import "./styles/account.css";
import "./styles/home.css";
import "./styles/notices.css";
import "./styles/agreements.css";
import "./styles/agreement-notice.css";
import "./styles/session.css";
import "./styles/history.css";
import "./styles/vouchers.css";
import "./styles/voucher-ticket.css";
import "./styles/stake.css";
import "./styles/share.css";
import "./styles/signature.css";
import "./styles/create.css";

import { createApp } from "vue";
import { Empty, List, Popup } from "vant";
import App from "./App.vue";

createApp(App).use(Popup).use(List).use(Empty).mount("#app");
